trigger fresh build of AFWall+ 2.9.4 after pyasn1 CI error
Necessary because build for 15940 broke with:

    ImportError: No module named 'pyasn1'

See https://gitlab.com/fdroid/fdroiddata/builds/13564758

Refs #637